"""
SecureMailScope X - Forensic Report & PDF Export Service
Generates authoritative, evidence-bounded forensic reports in JSON and PDF formats
strictly derived from deterministic backend analysis.
"""

import os
import io
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable
)
from reportlab.pdfgen import canvas

from app.schemas.api import (
    AnalysisDetailResponse,
    ForensicReportResponse,
    CaseMetadataDTO,
    ExecutiveSummaryDTO,
    SessionReportItemDTO,
    FindingReportItemDTO,
    EvidenceMappingItemDTO,
    CryptographicPostureDTO,
    PQCHNDLAssessmentDTO
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page numbers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(
                54,
                750,
                "SECUREMAILSCOPE X — FORENSIC CRYPTOGRAPHIC AUDIT REPORT"
            )
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Running Footer
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        footer_text = "CONFIDENTIAL & FORENSIC — Generated by SecureMailScope X Engine"
        self.drawString(54, 32, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_str)
        self.restoreState()


class ReportService:

    @classmethod
    def generate_report_model(cls, analysis: AnalysisDetailResponse) -> ForensicReportResponse:
        """
        Builds strongly typed ForensicReportResponse from AnalysisDetailResponse.
        """
        sessions = analysis.sessions or []
        protocols = sorted(list(set(s.protocol for s in sessions))) if sessions else ["UNKNOWN"]

        # 1. Case Metadata
        raw_frames = analysis.raw_capture_packets_total or analysis.total_packets_extracted
        metadata = CaseMetadataDTO(
            filename=analysis.file_name,
            analysis_id=analysis.analysis_id,
            file_size_bytes=analysis.file_size_bytes,
            raw_pcap_frame_count=raw_frames,
            reconstructed_session_count=analysis.email_sessions_found,
            protocols_detected=protocols,
            analysis_timestamp_utc=analysis.analysis_time_utc,
            tshark_version=analysis.tshark_version
        )

        # 2. Executive Summary
        primary_session = sessions[0] if sessions else None
        primary_grade = primary_session.security_assessment.grade if primary_session else "A"
        grade_score_map = {"A": 95, "B": 82, "C": 68, "D": 55, "F": 35}
        sec_score = grade_score_map.get(primary_grade, 75)

        health_score = primary_session.capture_health.score if primary_session else 100
        health_grade = primary_session.capture_health.grade if primary_session else "EXCELLENT"
        conf_score = primary_session.evidence_confidence.score if primary_session else 95
        conf_level = primary_session.evidence_confidence.level if primary_session else "HIGH"

        crit_count = sum(s.security_assessment.findings_summary.critical for s in sessions)
        high_count = sum(s.security_assessment.findings_summary.high for s in sessions)
        med_count = sum(s.security_assessment.findings_summary.medium for s in sessions)
        low_count = sum(s.security_assessment.findings_summary.low for s in sessions)
        info_count = sum(s.security_assessment.findings_summary.info for s in sessions)

        has_tls = any(s.tls and s.tls.negotiated_version for s in sessions)
        all_tls = all(s.tls and s.tls.negotiated_version for s in sessions) if sessions else False
        overall_posture = "100% Encrypted Sessions (TLS 1.3 Observed)" if all_tls else (
            "Mixed Encryption / Plaintext" if has_tls else "Unencrypted Plaintext Traffic"
        )

        exec_summary = ExecutiveSummaryDTO(
            security_grade=primary_grade,
            security_score=sec_score,
            capture_health_score=health_score,
            capture_health_grade=health_grade,
            evidence_confidence_score=conf_score,
            evidence_confidence_level=conf_level,
            critical_findings_count=crit_count,
            high_findings_count=high_count,
            medium_findings_count=med_count,
            low_findings_count=low_count,
            info_findings_count=info_count,
            overall_transport_posture=overall_posture,
            pqc_hndl_assessment_state="Assessment Incomplete — Exposure cannot be fully characterized from available passive key-exchange evidence."
        )

        # 3. Session Inventory
        session_items: List[SessionReportItemDTO] = []
        for s in sessions:
            tls_obj = s.tls
            pfs_st = tls_obj.pfs_status if tls_obj else "N/A (No TLS)"
            pqc_st = "Exposure cannot be fully characterized from available passive key-exchange evidence." if tls_obj else "Plaintext (No Protection)"

            session_items.append(SessionReportItemDTO(
                session_id=s.session_id,
                client=s.client,
                server=s.server,
                server_hostname=s.server_hostname,
                protocol=s.protocol,
                transport_mode=s.security_mode,
                starttls_state=s.starttls.state or "NONE",
                tls_version=tls_obj.negotiated_version if tls_obj else "None",
                cipher_suite=tls_obj.cipher_name if tls_obj else "None",
                certificate_visibility=tls_obj.certificate_visibility if tls_obj else "N/A",
                pfs_evidence_state=pfs_st,
                pqc_evidence_state=pqc_st
            ))

        # 4. Findings
        finding_items: List[FindingReportItemDTO] = []
        for s in sessions:
            for f in s.security_assessment.findings:
                # Standards reference derivation
                std_ref = "RFC 8446" if "TLS13" in f.id else (
                    "NIST FIPS 203" if "PQC" in f.id or "HNDL" in f.id else (
                        "RFC 3207" if "STARTTLS" in f.id else "NIST SP 800-52r2"
                    )
                )
                frames_display = f"Frames: {', '.join(map(str, f.evidence_frames))}" if f.evidence_frames else "Frame evidence unavailable"

                finding_items.append(FindingReportItemDTO(
                    severity=f.severity,
                    finding_id=f.id,
                    title=f.title,
                    description=f.description,
                    remediation=f.recommendation,
                    standards_reference=std_ref,
                    session_id=s.session_id,
                    native_frame_anchors=f.evidence_frames,
                    frame_anchors_display=frames_display
                ))

        # 5. Evidence Mapping
        evidence_items: List[EvidenceMappingItemDTO] = []
        for s in sessions:
            evidence_items.append(EvidenceMappingItemDTO(
                session_id=s.session_id,
                protocol=s.protocol,
                raw_capture_total_frames=raw_frames,
                session_packet_count=s.packets_count,
                advertised_frame=s.starttls.advertised_frame,
                requested_frame=s.starttls.requested_frame,
                accepted_frame=s.starttls.accepted_frame,
                client_hello_frame=s.tls.client_hello_frame if s.tls else None,
                server_hello_frame=s.tls.server_hello_frame if s.tls else None
            ))

        # 6. Cryptographic Posture
        tls_versions = sorted(list(set(s.tls.negotiated_version for s in sessions if s.tls and s.tls.negotiated_version)))
        cipher_suites = sorted(list(set(s.tls.cipher_name for s in sessions if s.tls and s.tls.cipher_name)))
        cert_vis = primary_session.tls.certificate_visibility if primary_session and primary_session.tls else "Encrypted / Unobservable"

        crypto_posture = CryptographicPostureDTO(
            tls_versions=tls_versions if tls_versions else ["None (Plaintext)"],
            cipher_suites=cipher_suites if cipher_suites else ["None"],
            transport_encryption_coverage="100% Encrypted" if all_tls else "Incomplete",
            certificate_visibility=cert_vis,
            forward_secrecy_evidence_state="Unknown / Insufficient passive evidence",
            legacy_crypto_exposure="None / 0 weak ciphers identified"
        )

        # 7. PQC / HNDL Assessment
        pqc_assessment = PQCHNDLAssessmentDTO(
            status="Assessment Incomplete",
            observed_key_exchange="Unknown / Insufficient passive evidence",
            hndl_exposure_summary="HNDL exposure cannot be fully characterized from available passive key-exchange evidence. Classical key exchange mechanisms are vulnerable to retroactive decryption by future quantum adversaries.",
            recommended_kem_standard="NIST FIPS 203 (ML-KEM)",
            standards_references=["NIST FIPS 203", "RFC 8446"]
        )

        # 8. Forensic Limitations
        limitations = [
            "TLS 1.3 encrypted handshake extensions and certificates are cryptographically unobservable by passive capture per RFC 8446 specification.",
            "Specific ephemeral key_share group parameters were not directly exposed in unencrypted packet headers.",
            "POP3 port 110 STLS real capture status remains pending/unavailable on live endpoints.",
            "Local cryptographic custody is implemented using SHA-256 capture sealing, canonical manifest sealing, and a hash-chained audit log. External blockchain/distributed-ledger notarization is not implemented."
        ]

        return ForensicReportResponse(
            case_metadata=metadata,
            executive_summary=exec_summary,
            session_inventory=session_items,
            findings=finding_items,
            evidence_mapping=evidence_items,
            cryptographic_posture=crypto_posture,
            pqc_hndl_assessment=pqc_assessment,
            forensic_limitations=limitations
        )

    @classmethod
    def generate_pdf_bytes(cls, analysis: AnalysisDetailResponse, actor: Optional[Any] = None) -> bytes:
        """
        Renders a clean, high-precision forensic PDF report.
        """
        report_data = cls.generate_report_model(analysis)
        meta = report_data.case_metadata
        exec_s = report_data.executive_summary

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Custom Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#475569"),
            spaceAfter=12
        )
        h2_style = ParagraphStyle(
            "SectionH2",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=colors.HexColor("#0f172a"),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=colors.HexColor("#1e293b")
        )
        body_bold = ParagraphStyle(
            "ReportBodyBold",
            parent=body_style,
            fontName="Helvetica-Bold"
        )
        table_cell = ParagraphStyle(
            "TableCell",
            parent=body_style,
            fontSize=7.5,
            leading=9.5
        )
        table_cell_bold = ParagraphStyle(
            "TableCellBold",
            parent=table_cell,
            fontName="Helvetica-Bold"
        )
        table_cell_cyan = ParagraphStyle(
            "TableCellCyan",
            parent=table_cell_bold,
            textColor=colors.HexColor("#0284c7")
        )
        finding_box_title = ParagraphStyle(
            "FindingBoxTitle",
            parent=body_style,
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#0f172a")
        )

        story = []

        # -------------------------------------------------------------------
        # Header Banner
        # -------------------------------------------------------------------
        story.append(Paragraph("SECUREMAILSCOPE X — PASSIVE FORENSIC AUDIT REPORT", title_style))
        story.append(Paragraph("Deterministic Cryptographic & Protocol Evidence Dissection", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284c7"), spaceAfter=10))

        # -------------------------------------------------------------------
        # 1. Case & Capture Metadata Table
        # -------------------------------------------------------------------
        meta_data = [
            [
                Paragraph("<b>Analysis ID:</b>", table_cell),
                Paragraph(meta.analysis_id, table_cell_bold),
                Paragraph("<b>Generated UTC:</b>", table_cell),
                Paragraph(meta.analysis_timestamp_utc, table_cell)
            ],
            [
                Paragraph("<b>Capture File:</b>", table_cell),
                Paragraph(meta.filename, table_cell_bold),
                Paragraph("<b>File Size:</b>", table_cell),
                Paragraph(f"{meta.file_size_bytes:,} bytes", table_cell)
            ],
            [
                Paragraph("<b>Raw PCAP Frames:</b>", table_cell),
                Paragraph(f"{meta.raw_pcap_frame_count:,} frames in capture", table_cell_cyan),
                Paragraph("<b>Reconstructed Sessions:</b>", table_cell),
                Paragraph(f"{meta.reconstructed_session_count} active session(s)", table_cell_bold)
            ],
            [
                Paragraph("<b>Dissector Engine:</b>", table_cell),
                Paragraph(meta.tshark_version, table_cell),
                Paragraph("<b>Protocols Detected:</b>", table_cell),
                Paragraph(", ".join(meta.protocols_detected), table_cell_bold)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[110, 150, 110, 134])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 8))

        # -------------------------------------------------------------------
        # 2. Executive Summary Scorecard Table
        # -------------------------------------------------------------------
        story.append(Paragraph("1. EXECUTIVE SECURITY & EVIDENCE SUMMARY", h2_style))

        summary_data = [
            [
                Paragraph("<b>Security Grade</b>", table_cell_bold),
                Paragraph("<b>Capture Health</b>", table_cell_bold),
                Paragraph("<b>Evidence Confidence</b>", table_cell_bold),
                Paragraph("<b>Findings Evaluated</b>", table_cell_bold)
            ],
            [
                Paragraph(f"<font size='12' color='#0284c7'><b>Grade {exec_s.security_grade}</b></font><br/>Score: {exec_s.security_score}/100", table_cell),
                Paragraph(f"<font size='12' color='#16a34a'><b>{exec_s.capture_health_score}%</b></font><br/>Status: {exec_s.capture_health_grade}", table_cell),
                Paragraph(f"<font size='12' color='#0284c7'><b>{exec_s.evidence_confidence_score}%</b></font><br/>Level: {exec_s.evidence_confidence_level}", table_cell),
                Paragraph(f"<font size='12'><b>{len(report_data.findings)} Total</b></font><br/>Crit: {exec_s.critical_findings_count} | High: {exec_s.high_findings_count} | Med: {exec_s.medium_findings_count} | Info: {exec_s.info_findings_count}", table_cell)
            ],
            [
                Paragraph("<b>Transport Posture:</b>", table_cell_bold),
                Paragraph(exec_s.overall_transport_posture, table_cell),
                Paragraph("<b>PQC / HNDL State:</b>", table_cell_bold),
                Paragraph(exec_s.pqc_hndl_assessment_state, table_cell)
            ]
        ]
        summary_table = Table(summary_data, colWidths=[120, 120, 120, 144])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 8))

        # -------------------------------------------------------------------
        # 3. Session Inventory Table
        # -------------------------------------------------------------------
        story.append(Paragraph("2. RECONSTRUCTED EMAIL SESSIONS INVENTORY", h2_style))

        sess_headers = [
            Paragraph("<b>Stream ID</b>", table_cell_bold),
            Paragraph("<b>Protocol & Mode</b>", table_cell_bold),
            Paragraph("<b>Endpoints (Src → Dst)</b>", table_cell_bold),
            Paragraph("<b>TLS Version & Cipher</b>", table_cell_bold),
            Paragraph("<b>Forward Secrecy</b>", table_cell_bold)
        ]
        sess_rows = [sess_headers]
        for s in report_data.session_inventory:
            sess_rows.append([
                Paragraph(s.session_id[:28] + "...", table_cell),
                Paragraph(f"{s.protocol} ({s.transport_mode})", table_cell_bold),
                Paragraph(f"{s.client}<br/>→ {s.server}", table_cell),
                Paragraph(f"{s.tls_version}<br/>{s.cipher_suite}", table_cell),
                Paragraph(s.pfs_evidence_state, table_cell)
            ])

        sess_table = Table(sess_rows, colWidths=[104, 100, 110, 110, 80])
        sess_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        # Fix text color in headers
        for i in range(len(sess_headers)):
            sess_headers[i].style.textColor = colors.white
        story.append(sess_table)
        story.append(Spacer(1, 8))

        # -------------------------------------------------------------------
        # 4. Forensic Evidence & Protocol Transitions Mapping
        # -------------------------------------------------------------------
        story.append(Paragraph("3. FORENSIC EVIDENCE & FRAME MAPPING", h2_style))

        ev_headers = [
            Paragraph("<b>Session Protocol</b>", table_cell_bold),
            Paragraph("<b>STARTTLS Advertised</b>", table_cell_bold),
            Paragraph("<b>STARTTLS Request</b>", table_cell_bold),
            Paragraph("<b>STARTTLS Accept</b>", table_cell_bold),
            Paragraph("<b>Client Hello</b>", table_cell_bold),
            Paragraph("<b>Server Hello</b>", table_cell_bold)
        ]
        ev_rows = [ev_headers]
        for em in report_data.evidence_mapping:
            ev_rows.append([
                Paragraph(f"{em.protocol} ({em.session_packet_count} frames)", table_cell_bold),
                Paragraph(f"Frame {em.advertised_frame}" if em.advertised_frame else "N/A", table_cell),
                Paragraph(f"Frame {em.requested_frame}" if em.requested_frame else "N/A", table_cell),
                Paragraph(f"Frame {em.accepted_frame}" if em.accepted_frame else "N/A", table_cell),
                Paragraph(f"Frame {em.client_hello_frame}" if em.client_hello_frame else "N/A", table_cell_cyan),
                Paragraph(f"Frame {em.server_hello_frame}" if em.server_hello_frame else "N/A", table_cell_cyan)
            ])

        ev_table = Table(ev_rows, colWidths=[104, 80, 80, 80, 80, 80])
        ev_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        for i in range(len(ev_headers)):
            ev_headers[i].style.textColor = colors.white
        story.append(ev_table)
        story.append(Spacer(1, 8))

        # -------------------------------------------------------------------
        # 5. Security & Cryptographic Findings
        # -------------------------------------------------------------------
        story.append(Paragraph("4. SECURITY FINDINGS & COMPLIANCE ASSESSMENT", h2_style))

        if report_data.findings:
            for f in report_data.findings:
                sev_color = colors.HexColor("#e11d48") if f.severity == "CRITICAL" else (
                    colors.HexColor("#f97316") if f.severity == "HIGH" else (
                        colors.HexColor("#eab308") if f.severity == "MEDIUM" else colors.HexColor("#0284c7")
                    )
                )

                f_content = [
                    [
                        Paragraph(f"<b>[{f.severity}] {f.title}</b>", finding_box_title),
                        Paragraph(f"<b>Standard:</b> {f.standards_reference} | <b>Anchors:</b> {f.frame_anchors_display}", table_cell)
                    ],
                    [
                        Paragraph(f"<b>Finding ID:</b> {f.finding_id}<br/><b>Description:</b> {f.description}", table_cell),
                        Paragraph(f"<b>Remediation / Recommendation:</b><br/>{f.remediation or 'N/A'}", table_cell)
                    ]
                ]
                f_table = Table(f_content, colWidths=[240, 264])
                f_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#ffffff")),
                    ("LINELEFT", (0, 0), (0, -1), 3, sev_color),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(KeepTogether([f_table, Spacer(1, 6)]))
        else:
            story.append(Paragraph("No security findings generated for this capture.", body_style))

        story.append(Spacer(1, 6))

        # -------------------------------------------------------------------
        # 6. Post-Quantum Cryptography & HNDL Risk
        # -------------------------------------------------------------------
        story.append(Paragraph("5. POST-QUANTUM READINESS & HNDL ASSESSMENT", h2_style))
        pqc = report_data.pqc_hndl_assessment

        pqc_data = [
            [
                Paragraph("<b>PQC Readiness Status:</b>", table_cell_bold),
                Paragraph(pqc.status, table_cell_cyan),
                Paragraph("<b>Observed Key Exchange:</b>", table_cell_bold),
                Paragraph(pqc.observed_key_exchange, table_cell)
            ],
            [
                Paragraph("<b>HNDL Exposure:</b>", table_cell_bold),
                Paragraph(pqc.hndl_exposure_summary, table_cell),
                Paragraph("<b>Standard Target:</b>", table_cell_bold),
                Paragraph(pqc.recommended_kem_standard, table_cell_bold)
            ]
        ]
        pqc_table = Table(pqc_data, colWidths=[110, 150, 110, 134])
        pqc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(pqc_table)
        story.append(Spacer(1, 8))

        # -------------------------------------------------------------------
        # 7. Forensic Boundaries & Limitations Notice
        # -------------------------------------------------------------------
        story.append(Paragraph("6. PASSIVE ANALYSIS BOUNDARIES & FORENSIC LIMITATIONS", h2_style))
        lim_text = "<br/>".join([f"• {lim}" for lim in report_data.forensic_limitations])
        lim_p = Paragraph(lim_text, table_cell)

        lim_table = Table([[lim_p]], colWidths=[504])
        lim_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#94a3b8")),
            ("LINELEFT", (0, 0), (0, -1), 3, colors.HexColor("#64748b")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(lim_table)

        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        
        # Record PDF Generation in Forensic Chain of Custody
        try:
            from app.services.custody_service import CustodyService
            CustodyService.record_report_generation(analysis.analysis_id, pdf_bytes, actor=actor)
        except Exception:
            pass
            
        return pdf_bytes
